name: Build
on:
    push:
        branches: [master]

    pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2

        - uses: actions/setup-node@v1
          with:
            node-version: '16'

        - name: Get composer cache directory
          id: composer-cache
          run: |
            echo "::set-output name=dir::$(composer config cache-files-dir)"

        - uses: actions/cache@v2
          with:
            path: ${{ steps.composer-cache.outputs.dir }}
            key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
            restore-keys: |
              ${{ runner.os }}-composer-

        - name: Install npm dependencies
          run: npm install

        - name: Install composer dependencies
          run: composer install --no-dev --no-interaction --prefer-dist

        - name: Build
          run: npm run production
